# -*- coding: utf-8 -*-
"""ppt_auto_conversion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fqbsln9F_b6LW4-Fe4sd38-c4Z8wE_dm
"""

pip install pandas

pip install python-pptx

from google.colab import drive
drive.mount('/content/gdrive/')

from pptx import Presentation
prs = Presentation('/content/gdrive/MyDrive/2학기 프로젝트/초본/Standard_ppt.pptx')

#첫 번째 슬라이드 레이아웃-논문 한글 제목, 논문 영어 제목, 이름, 소속 
add_slide_layout = prs.slide_layouts[0]
slide = prs.slides.add_slide(add_slide_layout)
# 슬라이드 내 개체 확인
shapes = slide.shapes
for shape in shapes:
  print(str(shape.placeholder_format.idx) + " : " + shape.name)

slide.placeholders[0].text = "논문 한글 제목 성공"
slide.placeholders[14].text = "학과 성공"
slide.placeholders[15].text = "이름 성공"
slide.placeholders[16].text = "논문 영어 제목 성공"
# 슬라이드 노트
notes_slide = slide.notes_slide
text_frame = notes_slide.notes_text_frame
text_frame.text = '텍스트 상자'

#두 번째 슬라이드 레이아웃-목차, 목차 예시                            
add_slide_layout = prs.slide_layouts[1]
slide = prs.slides.add_slide(add_slide_layout)
shapes = slide.shapes
for shape in shapes:
  print(str(shape.placeholder_format.idx) + " : " + shape.name)

slide.placeholders[0].text = "목차 성공"
slide.placeholders[15].text = "1. 서론 2. 연구 배경 성공"
# 슬라이드 노트
notes_slide = slide.notes_slide
text_frame = notes_slide.notes_text_frame
text_frame.text = '텍스트 상자'

#세 번째 슬라이드 레이아웃-참고문헌, 참고문헌 예시
add_slide_layout = prs.slide_layouts[2]
slide = prs.slides.add_slide(add_slide_layout)
shapes = slide.shapes
for shape in shapes:
  print(str(shape.placeholder_format.idx) + " : " + shape.name)

slide.placeholders[15].text = "김갑수(참고문헌) 성공"
slide.placeholders[0].text = "참고문헌 성공"
# 슬라이드 노트
notes_slide = slide.notes_slide
text_frame = notes_slide.notes_text_frame
text_frame.text = '텍스트 상자'

#네 번째 슬라이드 레이아웃-목차, 그림, 요약
add_slide_layout = prs.slide_layouts[3]
slide = prs.slides.add_slide(add_slide_layout)
shapes = slide.shapes
for shape in shapes:
  print(str(shape.placeholder_format.idx) + " : " + shape.name)

slide.placeholders[0].text = "결론(목차) 성공"
slide.placeholders[15].text = "요약 성공"
# 슬라이드 노트
notes_slide = slide.notes_slide
text_frame = notes_slide.notes_text_frame
text_frame.text = '텍스트 상자'
# 이미지 삽입 picture() 가로 안에 경로 
img = slide.placeholders[13]
img.insert_picture('/content/gdrive/MyDrive/2학기 프로젝트/apple.jpeg')

#다섯 번째 슬라이드 레이아웃-목차, 요약 *본문은 노트에 넣어야 됨*
add_slide_layout = prs.slide_layouts[4]
slide = prs.slides.add_slide(add_slide_layout)
shapes = slide.shapes
for shape in shapes:
  print(str(shape.placeholder_format.idx) + " : " + shape.name)

slide.placeholders[14].text = "목차 성공"
slide.placeholders[15].text = "1. 서론 2. 연구 배경 성공"
slide.placeholders[0].text = "목차 성공11"
# 슬라이드 노트
notes_slide = slide.notes_slide
text_frame = notes_slide.notes_text_frame
text_frame.text = '텍스트 상자'

add_slide_layout = prs.slide_layouts[5]
slide = prs.slides.add_slide(add_slide_layout)
shapes = slide.shapes
for shape in shapes:
  print(str(shape.placeholder_format.idx) + " : " + shape.name)

slide.placeholders[0].text = "Title 1 성공"
slide.placeholders[14].text = "Text Placeholder 2 성공"
slide.placeholders[15].text = "Text Placeholder 3 성공"
slide.placeholders[16].text = "Text Placeholder 4 성공"
# 슬라이드 노트
notes_slide = slide.notes_slide
text_frame = notes_slide.notes_text_frame
text_frame.text = '668979.'









prs.save('/content/gdrive/MyDrive/2학기 프로젝트/초본/Result_ppt.pptx')













